### ISSUE TITLE
Add upstream link

### ISSUE THREAD

**Issue by Uniminin** [kalmari246/exherbo-wiki#1]
https://github.com/kalmari246/exherbo-wiki/blob/master/openrc.md is the outdated version of my original guide https://github.com/Uniminin/exherbo-install-guide/wiki/Guide . And the guide is still under development. It needs proper testing, sanitization and a lot of fixes?
You may add the Upstream link.
UPSTREAM: https://github.com/Uniminin/exherbo-install-guide

**Comment by kalmari246** [comment]
sec
